export enum DONATION_STATE {
    CREATED = 'CREATED',
    READY_TO_TRAVEL = 'READY_TO_TRAVEL',
    IN_TRAVEL = 'IN_TRAVEL',
    FINALIZED = 'FINALIZED',
    DONATED_AGAIN = 'FINALIZED'
}

export enum NOTIFICATION_STATE {
    NEW = "NEW",
    READED = "READED"
}